nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.6.4.cjs
# there is a problem that yarn calulates checksums differently on Windows and Linux for git depenedencies,
# therefore `checksumBehavior: ignore` kills the yarn install and `checksumBehavior: update` messes yarn.lock
checksumBehavior: ignore
nmHoistingLimits: workspaces
