export const POPUP_FADE_IN_MS = 500
export const POPUP_FADE_OUT_MS = 500
export const POPUP_SHOW_MS = 1500
export const UNDERLINE_CHECK_INTERVAL_MS = 1000
export const WALLET_SLIDE_DURATION_MS = 100

export const PRICE_UPDATE_INTERVAL_MS = 10_000
export const PRICE_PRECISION_DIGITS = 8
export const PRICE_PRECISION = BigInt(10 ** PRICE_PRECISION_DIGITS)

export const WALLET_INFO_UPDATE_INTERVAL_MS = 10_000

export const MAX_AVAX_DECIMALS_DISPLAY = 5
export const MAX_KUCOCOIN_DECIMALS_DISPLAY = 4

// dex
export const DEX_FACTOR_BIPS = BigInt(997)
export const DEX_MAX_BIPS = BigInt(1000)