export const UNDERLINE_CHECK_INTERVAL_MS = 1000
export const WALLET_SLIDE_DURATION_MS = 100

export const PRICE_UPDATE_INTERVAL_MS = 10_000
export const PRICE_PRECISION_DIGITS = 9
export const PRICE_PRECISION = BigInt(10 ** PRICE_PRECISION_DIGITS)

export const WALLET_INFO_UPDATE_INTERVAL_MS = 10_000
export const WALLET_INFO_UPDATE_OFFSET_S = 2

export const MAX_AVAX_DECIMALS_DISPLAY = 6
export const MAX_KUCOCOIN_DECIMALS_DISPLAY = 2