on:
  push:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn parcel-build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target-branch: gh-pages
          build_dir: build